---
language: python

jobs:
  include:
    - stage: Lint
      python:
        - 3.6
        - 3.7
      before_install:
        - python --version
        - pip install -U pip
        - pip install -U flake8
      script: grep -rl '^#!/.*py' | xargs -n1 flake8 --extend-ignore=E501
