---
language: python

jobs:
  include:
    - stage: Lint
    - name: "Lint Python 3.6"
      python:
        - 3.6
      before_install:
        - python --version
        - pip install -U pip
        - pip install -U flake8
      script: grep -rl '^#!/.*py' | xargs -n1 flake8 --extend-ignore=E501

    - name: "Lint Python 3.7"
      python:
        - 3.7
      before_install:
        - python --version
        - pip install -U pip
        - pip install -U flake8
      script: grep -rl '^#!/.*py' | xargs -n1 flake8 --extend-ignore=E501
